### PR TITLE
Add and improve some translations

### PR DESCRIPTION
**Pull request by xianfengting**
- [x] 我已经检查文件路径正确，即 `project/assets/模组id/lang/zh_cn.lang`；
- [x] 我已确定语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已经阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

### CODE REVIEW

**Comment by xianfengting** [comment]
@TartaricAcid Please have a look.

**Comment by dovisutu** [comment]
I'm not sure (and I'm not 943), but maybe you need to delete the `translate diff generetor`'s comment.
You can wait for tartaric_acid for a proper review.
PS: 你可以在这里说中文。

**Comment by Chenwe-i-lin** [comment]
我感觉我行了，希望不会被943锤（

**Comment by xianfengting** [comment]
> I'm not sure (and I'm not 943), but maybe you need to delete the `translate diff generetor`'s comment.
> You can wait for tartaric_acid for a proper review.
> PS: 你可以在这里说中文。

Thanks for your warning. I'll pay attention next time(because I'm new here).  
And the reason why I speak English is that it's inconvenient for me to change my input method between Chinese and English.

**Comment by xianfengting** [comment]
> 我感觉我行了，希望不会被943锤（

I hope 943 will excuse me because I do not understand most of the rules in this project.

**Comment by Chenwe-i-lin** [comment]
> I hope 943 will excuse me because I do not understand most of the rules in this project.

me too. but what is "ummxxxxxxxxxxxx(number)"?

**Comment by xianfengting** [comment]
> > I hope 943 will excuse me because I do not understand most of the rules in this project.
> 
> me too. but what is "ummxxxxxxxxxxxx(number)"?

I don't know. Maybe it's a name of a Mod.

**Pull request merged**
